env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - AWS_BUCKET=hornblower-builds
  - secure: "WOJphl9q2lRXCTPuCimoLuK72YxzBH5a/AOgmP+GG1iQOx5dI4UeuwdoQeCb6Vt7FRZzxB6yaRrpHAD5KPa3Ftp0L9jbv4YAle7VEiQNR434TO5/oGjC3zsKXOSKKvCRSbT3bOnVjF/mTSLjOxAvWhFtup9XzX1DyWY3fE8UfeTS311Y0DLCQXbZZox/ElEJCUZq4QgjBEZTzT6RJONE3BPUL2nFueR6NtbboSz7CTAzlHeJKLxg4WJQScBG0/KtUGREF1leVi8Y/RJuD1GdsnzcadnMuFJ8uXoEXvj5yV+x1kzjdP5Ep7bcLjkTsCRhP41jsWQPjUEWf6z3BqT8EJimMvuMfZY1v+QwsUetgEN1CtAovq6rXt6p6fEwAvPKpG+f2UDJI68bBwlOPj83fvHtFofWYyc2kfgR4pmfKYq9bJE2IW9P4yZl74Kl+Q3ngmcg4nLN6vpep3yYp8jxaJWgVtqRuPaycMHdq0ZzMZZtdJxqrs/04qXsZVyfbtsd8Idzt75k/MfZ87+bthnkeWicKopQbL2erOWBwtkoRqqitOn4J1oMmuMe19NeQRRk+LmaaX2bVl64K4IMkRq5TU2vj7mHGg/okzqhcicuvX2Z+9HKGcmDCaJowrp207jZL56QGFCxEukkujCAJa9gwS31UGYHj7hvd9OjF60iNtw="
  - secure: "PZ2pEPug1vPoxmQKOnH7BqI5mZg28Iq74Iuuqzrcb8eke7C0f4FIcnbSqqn6xxLO3rUekIwoj6ed0b5HFqaGFmZmFSDszPgfkEaL8xYBeBZkkP0YeiKAvyJbYOwnVM6frJ25zvdKXRCAZOV/AGqlIq++k1Te4xnMKtO3OxWiQAXSMQ8W3J5BSwKqmDEzepYXCSoJ7J1StcOGZo7k7kDGyFej8ULiC39LOHxJfLnoQTdv+xEje4FOlnyPvjJGerq2G4hVQysesVJukS5UwvcQGNuJVYYBpFBAzpPFhk26kuovxqSccV/NLJ8w1t3bbJl+nFKmK1LwjLH0Z6XLaSJeHBa/+uN1KOcYzwKmYUqqO5fni46PCG4RehlPwbbkEDE4RY57XxAuEoWRg1KFFpHeTYnUmSx3YJ2E3c9Hl6kLti+FKTTx2VPIbKv5gAp/i8Yse9sLjd6Ym/6IlK+9Np8t3ml3WpVVnKBvBgTNMQyTU8rvHjfT45/HlPiOoX+v/Hwz3U8UGKb0DxbYHJ6SCQHG99+Y8Anrog2KqYjTEQ87uuwfn6MAbY7TV38roEKfwhJ7YnpVu8t3kLs2aEPsw7618u3FWu3e2FdGDiP7McC2364TSThzYTV8EamLHJB0MX+KgHTh8X5coZoTdjoFvmqEIGwzFbpXzwVON7ws/ZlCtUQ="

language: php
php: 7.0
# Skip running any tests
script: phpunit --version

notifications:
  slack:
    secure: "VSw+NilNUpESLecqxUZeLPc2R3qLQFHnupDmLD4voW1D8EByG3uxNiTvfdp8Nq+JV5bB4FLiZ+EACIGje7QtyjU/t0QGbwyu9y5JTKnGANqFJZMMursmKvaeSZVh+983II1cb8QH00Htcit7NdcQNudeLzSL1XK0dHzft8YQmPwYRITl56G6jWCYXeBTAQF947WB5+CByM5YxE0wf1BXuXIe/zDPZ6dqFTD03tq3aqKyHS6RAjV5eAkmSJeHXUxJiUFx4PBZZB2KsDa8jdVRD95t8zTpXiciRA3SkyhfhSeFPA25MjKQU4We7JeyuvhDx5C6MNB5O3N+Gep1jV1vJv/KWxG+63KYwbv7jwMEXFj1ZXE7Il/uVjlpdNJo81qlvNCkUTBzUNoMZM8LYE6c46l5/zXNqgtRSEKJnQNiJPaQRMs97AlfQ2LBerFm6qGu5WVQnUnUUJTfm0nZji2E/xN0ChEvhDskbOF/sF7f4jYkRLtskB6IhDorh2Ufg/jaTkkbIyKSR76df0KUTuvNX5hmMHNkeDqmpN01gRhLrbMT0xd9RRj5XW0VmVdMTELcHq7zMN99yrIfyAuURu+wABSu1rWJyzZmjCgNti6PVC9jfm+O0vgqxcs90fCVX8olNkduQxBeDR71yi2hiCrJUtjR3JwLS+FXgt3AAGr/jSQ="

before_deploy:
  - pip install --user boto3
  - rm -rf "${TRAVIS_BUILD_DIR}"/.git

deploy:
- provider: script
  skip_cleanup: true
  script: python build_artifact.py staging
  on:
    branch: staging
- provider: script
  skip_cleanup: true
  script: python build_artifact.py production
  on:
    branch: production
