env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - AWS_BUCKET=hornblower-builds
  - secure: "QFhmoRNVOq/FsgQ4SmJWd7S++QkTi2fYvKS5QPeM1MVZjwEcf1RaO8wGhESFvdLMuKWyOEHGfpq6qEvlRj/B2wXLWQkgq8Cmw1zwZUaImQ5RwjbbJi4II9ed6mNEmpbdE4uu0ajdCkpxIuKnL+Ll257BnhFsIW2kZkNqSR0dnR35qp61FN/yNQ2qbatqe7OWbvdG0PxHKhcAvyaOEoTYcfNuPaqIX4dWnyzg5W9tyQ8Gdrz/ueJsvdI839ogE5cb5crZChwZnSO3toW+N6HuGhlNN/zIYBbQXhsrDg1zYw4Pr1becfH5hly+ThLF1cAvTqdnsAtxfgoauKzwTwvF+UMfB9UDFYvin6/wVj/Lg5TPcxgk8slI5AgZV1bPyEQ8QcYmTT0BGQLJ9ugBijQoFN74XbhC/iDkc5TtkbBsOS8S5qOUOoXUJo8wqYcFoqZ1n39k4eZsu8kxVL6f47ZdvD4/Nbcrak9F9Q/K1XjtKDSUGUUTPrrDmqWzymNWUls/SOl9/nuBNT4vg5NrB19piP7qV0ZYTONip3xyCpV0j2k8Ontq7BjG/tN/SIKUxXoX0CXJO61v6czNgsWjGTe4xf8uwt3K1oSejwsrQZF59+A9oNOBqcvrgneIqupTRHkwPopaJlaOGBueZ1A4r+13nciGT2fLitvALvlKzuYlR3o="
  - secure: "R86mG0qkXcUMwGVEvauzMu/p0eTTsAXHMRDj7zESMDOdSJaRxsC9B1YM/Usvz5V4N/tciDwkp2coXW1Zzj76D686VEFjelPL4zMdaydISiN8EZi1uKXnAxF76P7bl7WQN63MQxpsoMXyyqelrhCjUZ/QilMyWxXNa5rN3WaIDsZz/uPlssLRTHx4xJQNwC89GRp+gHDueDYNckxUkbwV7Cm/FQo0In9I/0HiE/AwFNxYY15pAQCr/q1qngrrHTDCcrr3YMqYb+NKHNw/ei+1hgvzc9IsxCzC9cDwJfPe9wTJvTP0vkcZNOwDLSBU3JTh5pCjTsXmDwVWVwY4TcxwQQt6c6573ZcmUWW1hvI4fvRaqKoNT14U72H5DDZuichG3u94NEcve1nLVNo3Ryt59Z3kJOwbAJ60yJiLZmc/wxzSs1q7c6TP/yT+Yr1V2xi0GyJLrNNcpuAb1pteKeApTBR6ZIusJM1pufxbFa6dM5ImfFvYaMdGffol56xzuMkkoVAT1eILjkXmtDnUwMrHuIzejspSLZBJ2tFra8r5O0SSoN1qirK+bjI5e94HxUDQ/A2d9KVbv0+/K1XoW5n6AmxQ89fBQxiNZcPF/f+zxyif4HeMhf0fxyiWvID3l5eX4TzEBRENayK8MbKK47kw7mf6AtHGoOHuqLIF1ewNyNo="

language: php
php: 7.0
# Skip running any tests
script: phpunit --version

notifications:
  slack:
    secure: "BroQKGIGE6oo1TMRNvdG+h9qbaKvu0VbpVpGWvskTl0+dOhid3CsyOpJupL/0thQRMgMBfd1ySnY9ntsBj2fmkFSTNdcUkLOs7TPWIgIvkJRsrNp0HjfWByCTWjJXwQFzK2XRrq2BprRCP3Fu0+V4fec1l2yO8/6hg+7wxWWYTman1tdDI9UzKhSa+wMdyzMF3mNbmA6H9e1BUXougO6OZIhGy14kYE7MtMLWpjd0Sz/x0bP9AoTdgvysAdu2GgWEctsqufXQHfZJG/q22mfaPlxBR0G36zBkNMDnu02PtplzbV6pVGHmATTaz37ifG6RXpe3x24tXdus3JQU0U+vOU5IplWlUxoy6uMBjT5m46ISmvOX8NniZxFt2g+x+a5giSWntQQ6spNeRlkh39OeP9iz+MmlgqNWs3c/mj7VfHTRkTiEiwMwmE2/ZY/AqMXMCx3TdTDOuEKBl7vuboHxBJ4GgDyhCLxnSF22TKYURZ5XzbLeBmCbyf4MVXYDQ9pbXibkfikviNPOn1bUWIKd2cWaCAgST8zrI6XnKSlFGZL3mCrSFITgNEj5TZE1x9dA8K94sOLom2YQsqnxQsQD6WMXPqFzjyfEDU+B1dzUqQ/mHV1/9m6aPPcI9vNFMvOZPUGEfG5dQXcxNz90LvehmTFzVOcXGNv2qt+Rr7V7X0="

before_deploy:
  - pip install --user boto3
  - rm -rf "${TRAVIS_BUILD_DIR}"/.git

deploy:
- provider: script
  skip_cleanup: true
  script: python build_artifact.py staging
  on:
    branch: staging
- provider: script
  skip_cleanup: true
  script: python build_artifact.py production
  on:
    branch: production
